package semester_i.other;

import java.text.DecimalFormat;
import java.util.Scanner;

public class NumberGuesser {

    /*
     * Simulates rolling of two dies' values combined [Math.random() returns 0.0 to 0.9 repeating, multiply by 10 -> 0.0 to 9.0, cast to int, add three].
     * Used the above so that the randomization is truly random, and not generated by a seed which results in obvious patterns, as seen with Random.nextInt(exclusive int).
     * Calculates average amount of tries (1 to 4), as an integer if possible, otherwise a double, as well as percentage of correct guesses.
     * Sentinel value is 1337, to force close the game.
     * Uncomment the commented-out line to easily debug the generated number.
     * Don't mind the ternary, it's simply more convenient.
     */
    public static void main(String... args) {
        DecimalFormat decimalFormat = new DecimalFormat("###.##");
        Scanner scanner = new Scanner(System.in);
        int answer;
        int rounds = 0;
        int totalGuesses = 0;
        boolean guessed;
        System.out.println("Enter the sentinel value 1337 for the program to force close.");
        iterator:
        while (true) {
            answer = (int) (10 * Math.random()) + 3;
            System.out.println("\n" + "---------------New Round Commencing!---------------");
            //System.out.println("The generated number is: " + answer);
            int guesses = 0;
            System.out.print("Guess a number: ");
            do {
                int input = scanner.nextInt();
                guesses++;
                totalGuesses++;
                if (input == 1337) {
                    totalGuesses -= guesses;
                    System.out.println("You have ended the game prematurely.");
                    break iterator;
                } else if (input == answer) {
                    guessed = true;
                    rounds++;
                    break;
                } else {
                    guessed = false;
                    if (guesses == 4) {
                        rounds++;
                        System.out.println(input + " was not the correct answer.");
                    } else {
                        System.out.print(input + " was not the correct answer, guess again: ");
                    }
                }
            } while (guesses < 4);
            System.out.println(guessed ? "You guessed the correct number in " + guesses + (guesses > 1 ? " tries" : " try") + ", the number was " + answer + "." : "You never guessed the number, the number was " + answer + ".");
        }
        scanner.close();
        String avg = String.valueOf((double) totalGuesses / rounds);
        int iAverage = avg.indexOf(".") == avg.length() - 2 && avg.charAt(avg.length() - 1) == '0' ? Integer.parseInt(avg.split("\\.")[0]) : -1;
        double dAverage = iAverage == -1 ? Double.parseDouble(avg) : -1.0;
        System.out.println("\nIn " + rounds + (rounds > 1 ? " rounds" : " round") + ", it took you an average of " + (iAverage != -1 ? decimalFormat.format(iAverage) + (iAverage > 1 ? " tries" : " try") : decimalFormat.format(dAverage) + (dAverage > 1 ? " tries" : " try")) + " to guess the number (" + decimalFormat.format((double) rounds / totalGuesses * 100) + "%).");
    }
}